In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load legality
legality_df = pd.read_csv("../resources/State_Legality_Cannabis.csv")
legality_df.head()

        State  Recreational  Rec Year Legalized  Medical  Med Year Legalized
0     Alabama             0                 0.0        1                2021
1      Alaska             1              2014.0        1                1998
2     Arizona             1              2020.0        1                2010
3    Arkansas             0                 0.0        1                2016
4  California             1              2016.0        1                1996

In [3]:
# Get Data Types
legality_df.dtypes

State                  object
Recreational            int64
Rec Year Legalized    float64
Medical                 int64
Med Year Legalized      int64
dtype: object

In [4]:
# fill null values with 0
legality_df = legality_df.fillna(0)
legality_df.head()

        State  Recreational  Rec Year Legalized  Medical  Med Year Legalized
0     Alabama             0                 0.0        1                2021
1      Alaska             1              2014.0        1                1998
2     Arizona             1              2020.0        1                2010
3    Arkansas             0                 0.0        1                2016
4  California             1              2016.0        1                1996

In [5]:
# Convert Rec Year Legalized to int64
legality_df["Rec Year Legalized"] = legality_df["Rec Year Legalized"].astype(int)
legality_df

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized
0,Alabama,0,0,1,2021
1,Alaska,1,2014,1,1998
2,Arizona,1,2020,1,2010
3,Arkansas,0,0,1,2016
4,California,1,2016,1,1996
5,Colorado,1,2012,1,2000
6,Connecticut,1,2021,1,2012
7,Delaware,0,0,1,2011
8,District of Columbia,1,2015,1,2011
9,Florida,0,0,1,2016
10,Georgia,0,0,1,2015
11,Hawaii,0,0,1,2000
12,Idaho,0,0,0,0
13,Illinois,1,2019,1,2013
14,Indiana,0,0,0,0
15,Iowa,0,0,1,2017
16,Kansas,0,0,0,0
17,Kentucky,0,0,0,0
18,Louisiana,0,0,1,2015
19,Maine,1,2016,1,1999
20,Maryland,0,0,1,2013
21,Massachusetts,1,2016,1,2012
22,Michigan,1,2018,1,2008
23,Minnesota,0,0,1,2014
24,Mississippi,0,0,1,2022
25,Missouri,0,0,1,2018
26,Montana,1,2020,1,2004
27,Nebraska,0,0,0,0
28,Nevada,1,2016,1,1998
29,New Hampshire,0,0,1,2013
30,New Jersey,1,2020,1,2010
31,New Mexico,1,2021,1,2007
32,New York,1,2021,1,2014
33,North Carolina,0,0,0,0
34,North Dakota,0,0,1,2016
35,Ohio,0,0,1,2016
36,Oklahoma,0,0,1,2018
37,Oregon,1,2014,1,1998
38,Pennsylvania,0,0,1,2016
39,Rhode Island,1,2022,1,2006
40,South Carolina,0,0,0,0
41,South Dakota,0,0,1,2020
42,Tennessee,0,0,0,0
43,Texas,0,0,0,0
44,Utah,0,0,1,2018
45,Vermont,1,2020,1,2004
46,Virginia,1,2021,1,2020
47,Washington,1,2012,1,1998
48,West Virginia,0,0,1,2017
49,Wisconsin,0,0,0,0
50,Wyoming,0,0,0,0

In [6]:
legality_df.dtypes

State                 object
Recreational           int64
Rec Year Legalized     int64
Medical                int64
Med Year Legalized     int64
dtype: object

In [7]:
# recreationally legal
yrs_rec = legality_df[legality_df["Recreational"] == 1]
yrs_rec

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized
1,Alaska,1,2014,1,1998
2,Arizona,1,2020,1,2010
4,California,1,2016,1,1996
5,Colorado,1,2012,1,2000
6,Connecticut,1,2021,1,2012
8,District of Columbia,1,2015,1,2011
13,Illinois,1,2019,1,2013
19,Maine,1,2016,1,1999
21,Massachusetts,1,2016,1,2012
22,Michigan,1,2018,1,2008
26,Montana,1,2020,1,2004
28,Nevada,1,2016,1,1998
30,New Jersey,1,2020,1,2010
31,New Mexico,1,2021,1,2007
32,New York,1,2021,1,2014
37,Oregon,1,2014,1,1998
39,Rhode Island,1,2022,1,2006
45,Vermont,1,2020,1,2004
46,Virginia,1,2021,1,2020
47,Washington,1,2012,1,1998

In [8]:
yrs_rec['Years legal (rec)'] = 2022 - legality_df['Rec Year Legalized']
yrs_rec['Years legal (med)'] = 2022 - legality_df['Med Year Legalized']
yrs_rec

/var/folders/v_/71ttg5mx0klbw6xrch11mh200000gp/T/ipykernel_7303/3824716492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yrs_rec['Years legal (rec)'] = 2022 - legality_df['Rec Year Legalized']
/var/folders/v_/71ttg5mx0klbw6xrch11mh200000gp/T/ipykernel_7303/3824716492.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yrs_rec['Years legal (med)'] = 2022 - legality_df['Med Year Legalized']

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
1,Alaska,1,2014,1,1998,8,24
2,Arizona,1,2020,1,2010,2,12
4,California,1,2016,1,1996,6,26
5,Colorado,1,2012,1,2000,10,22
6,Connecticut,1,2021,1,2012,1,10
8,District of Columbia,1,2015,1,2011,7,11
13,Illinois,1,2019,1,2013,3,9
19,Maine,1,2016,1,1999,6,23
21,Massachusetts,1,2016,1,2012,6,10
22,Michigan,1,2018,1,2008,4,14
26,Montana,1,2020,1,2004,2,18
28,Nevada,1,2016,1,1998,6,24
30,New Jersey,1,2020,1,2010,2,12
31,New Mexico,1,2021,1,2007,1,15
32,New York,1,2021,1,2014,1,8
37,Oregon,1,2014,1,1998,8,24
39,Rhode Island,1,2022,1,2006,0,16
45,Vermont,1,2020,1,2004,2,18
46,Virginia,1,2021,1,2020,1,2
47,Washington,1,2012,1,1998,10,24

In [9]:
# medically legal
yrs_med = legality_df[legality_df["Medical"] == 1]
yrs_med.head()

        State  Recreational  Rec Year Legalized  Medical  Med Year Legalized
0     Alabama             0                   0        1                2021
1      Alaska             1                2014        1                1998
2     Arizona             1                2020        1                2010
3    Arkansas             0                   0        1                2016
4  California             1                2016        1                1996

In [10]:
# Years medically legal
yrs_med['Years legal (med)'] = 2022 - legality_df['Med Year Legalized']
yrs_med

/var/folders/v_/71ttg5mx0klbw6xrch11mh200000gp/T/ipykernel_7303/1161284867.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yrs_med['Years legal (med)'] = 2022 - legality_df['Med Year Legalized']

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (med)
0,Alabama,0,0,1,2021,1
1,Alaska,1,2014,1,1998,24
2,Arizona,1,2020,1,2010,12
3,Arkansas,0,0,1,2016,6
4,California,1,2016,1,1996,26
5,Colorado,1,2012,1,2000,22
6,Connecticut,1,2021,1,2012,10
7,Delaware,0,0,1,2011,11
8,District of Columbia,1,2015,1,2011,11
9,Florida,0,0,1,2016,6
10,Georgia,0,0,1,2015,7
11,Hawaii,0,0,1,2000,22
13,Illinois,1,2019,1,2013,9
15,Iowa,0,0,1,2017,5
18,Louisiana,0,0,1,2015,7
19,Maine,1,2016,1,1999,23
20,Maryland,0,0,1,2013,9
21,Massachusetts,1,2016,1,2012,10
22,Michigan,1,2018,1,2008,14
23,Minnesota,0,0,1,2014,8
24,Mississippi,0,0,1,2022,0
25,Missouri,0,0,1,2018,4
26,Montana,1,2020,1,2004,18
28,Nevada,1,2016,1,1998,24
29,New Hampshire,0,0,1,2013,9
30,New Jersey,1,2020,1,2010,12
31,New Mexico,1,2021,1,2007,15
32,New York,1,2021,1,2014,8
34,North Dakota,0,0,1,2016,6
35,Ohio,0,0,1,2016,6
36,Oklahoma,0,0,1,2018,4
37,Oregon,1,2014,1,1998,24
38,Pennsylvania,0,0,1,2016,6
39,Rhode Island,1,2022,1,2006,16
41,South Dakota,0,0,1,2020,2
44,Utah,0,0,1,2018,4
45,Vermont,1,2020,1,2004,18
46,Virginia,1,2021,1,2020,2
47,Washington,1,2012,1,1998,24
48,West Virginia,0,0,1,2017,5

In [14]:
# merge years_rec with years_med
years_df = pd.merge(yrs_rec, yrs_med, on=['Rec Year Legalized', 'State', 'Recreational', 'Medical', 'Years legal (med)', 'Med Year Legalized'], how='outer')
years_df

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Alaska,1,2014,1,1998,8.0,24
1,Arizona,1,2020,1,2010,2.0,12
2,California,1,2016,1,1996,6.0,26
3,Colorado,1,2012,1,2000,10.0,22
4,Connecticut,1,2021,1,2012,1.0,10
5,District of Columbia,1,2015,1,2011,7.0,11
6,Illinois,1,2019,1,2013,3.0,9
7,Maine,1,2016,1,1999,6.0,23
8,Massachusetts,1,2016,1,2012,6.0,10
9,Michigan,1,2018,1,2008,4.0,14
10,Montana,1,2020,1,2004,2.0,18
11,Nevada,1,2016,1,1998,6.0,24
12,New Jersey,1,2020,1,2010,2.0,12
13,New Mexico,1,2021,1,2007,1.0,15
14,New York,1,2021,1,2014,1.0,8
15,Oregon,1,2014,1,1998,8.0,24
16,Rhode Island,1,2022,1,2006,0.0,16
17,Vermont,1,2020,1,2004,2.0,18
18,Virginia,1,2021,1,2020,1.0,2
19,Washington,1,2012,1,1998,10.0,24
20,Alabama,0,0,1,2021,NaN,1
21,Arkansas,0,0,1,2016,NaN,6
22,Delaware,0,0,1,2011,NaN,11
23,Florida,0,0,1,2016,NaN,6
24,Georgia,0,0,1,2015,NaN,7
25,Hawaii,0,0,1,2000,NaN,22
26,Iowa,0,0,1,2017,NaN,5
27,Louisiana,0,0,1,2015,NaN,7
28,Maryland,0,0,1,2013,NaN,9
29,Minnesota,0,0,1,2014,NaN,8
30,Mississippi,0,0,1,2022,NaN,0
31,Missouri,0,0,1,2018,NaN,4
32,New Hampshire,0,0,1,2013,NaN,9
33,North Dakota,0,0,1,2016,NaN,6
34,Ohio,0,0,1,2016,NaN,6
35,Oklahoma,0,0,1,2018,NaN,4
36,Pennsylvania,0,0,1,2016,NaN,6
37,South Dakota,0,0,1,2020,NaN,2
38,Utah,0,0,1,2018,NaN,4
39,West Virginia,0,0,1,2017,NaN,5

In [15]:
# Replace NaN with 0
years_df = years_df.fillna(0)
years_df

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Alaska,1,2014,1,1998,8.0,24
1,Arizona,1,2020,1,2010,2.0,12
2,California,1,2016,1,1996,6.0,26
3,Colorado,1,2012,1,2000,10.0,22
4,Connecticut,1,2021,1,2012,1.0,10
5,District of Columbia,1,2015,1,2011,7.0,11
6,Illinois,1,2019,1,2013,3.0,9
7,Maine,1,2016,1,1999,6.0,23
8,Massachusetts,1,2016,1,2012,6.0,10
9,Michigan,1,2018,1,2008,4.0,14
10,Montana,1,2020,1,2004,2.0,18
11,Nevada,1,2016,1,1998,6.0,24
12,New Jersey,1,2020,1,2010,2.0,12
13,New Mexico,1,2021,1,2007,1.0,15
14,New York,1,2021,1,2014,1.0,8
15,Oregon,1,2014,1,1998,8.0,24
16,Rhode Island,1,2022,1,2006,0.0,16
17,Vermont,1,2020,1,2004,2.0,18
18,Virginia,1,2021,1,2020,1.0,2
19,Washington,1,2012,1,1998,10.0,24
20,Alabama,0,0,1,2021,0.0,1
21,Arkansas,0,0,1,2016,0.0,6
22,Delaware,0,0,1,2011,0.0,11
23,Florida,0,0,1,2016,0.0,6
24,Georgia,0,0,1,2015,0.0,7
25,Hawaii,0,0,1,2000,0.0,22
26,Iowa,0,0,1,2017,0.0,5
27,Louisiana,0,0,1,2015,0.0,7
28,Maryland,0,0,1,2013,0.0,9
29,Minnesota,0,0,1,2014,0.0,8
30,Mississippi,0,0,1,2022,0.0,0
31,Missouri,0,0,1,2018,0.0,4
32,New Hampshire,0,0,1,2013,0.0,9
33,North Dakota,0,0,1,2016,0.0,6
34,Ohio,0,0,1,2016,0.0,6
35,Oklahoma,0,0,1,2018,0.0,4
36,Pennsylvania,0,0,1,2016,0.0,6
37,South Dakota,0,0,1,2020,0.0,2
38,Utah,0,0,1,2018,0.0,4
39,West Virginia,0,0,1,2017,0.0,5

In [16]:
# Data type check
years_df.dtypes

State                  object
Recreational            int64
Rec Year Legalized      int64
Medical                 int64
Med Year Legalized      int64
Years legal (rec)     float64
Years legal (med)       int64
dtype: object

In [17]:
# Convert to int
years_df['Years legal (rec)'] = years_df['Years legal (rec)'].astype(int)

In [18]:
years_df.dtypes

State                 object
Recreational           int64
Rec Year Legalized     int64
Medical                int64
Med Year Legalized     int64
Years legal (rec)      int64
Years legal (med)      int64
dtype: object

In [19]:
years_df

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Alaska,1,2014,1,1998,8,24
1,Arizona,1,2020,1,2010,2,12
2,California,1,2016,1,1996,6,26
3,Colorado,1,2012,1,2000,10,22
4,Connecticut,1,2021,1,2012,1,10
5,District of Columbia,1,2015,1,2011,7,11
6,Illinois,1,2019,1,2013,3,9
7,Maine,1,2016,1,1999,6,23
8,Massachusetts,1,2016,1,2012,6,10
9,Michigan,1,2018,1,2008,4,14
10,Montana,1,2020,1,2004,2,18
11,Nevada,1,2016,1,1998,6,24
12,New Jersey,1,2020,1,2010,2,12
13,New Mexico,1,2021,1,2007,1,15
14,New York,1,2021,1,2014,1,8
15,Oregon,1,2014,1,1998,8,24
16,Rhode Island,1,2022,1,2006,0,16
17,Vermont,1,2020,1,2004,2,18
18,Virginia,1,2021,1,2020,1,2
19,Washington,1,2012,1,1998,10,24
20,Alabama,0,0,1,2021,0,1
21,Arkansas,0,0,1,2016,0,6
22,Delaware,0,0,1,2011,0,11
23,Florida,0,0,1,2016,0,6
24,Georgia,0,0,1,2015,0,7
25,Hawaii,0,0,1,2000,0,22
26,Iowa,0,0,1,2017,0,5
27,Louisiana,0,0,1,2015,0,7
28,Maryland,0,0,1,2013,0,9
29,Minnesota,0,0,1,2014,0,8
30,Mississippi,0,0,1,2022,0,0
31,Missouri,0,0,1,2018,0,4
32,New Hampshire,0,0,1,2013,0,9
33,North Dakota,0,0,1,2016,0,6
34,Ohio,0,0,1,2016,0,6
35,Oklahoma,0,0,1,2018,0,4
36,Pennsylvania,0,0,1,2016,0,6
37,South Dakota,0,0,1,2020,0,2
38,Utah,0,0,1,2018,0,4
39,West Virginia,0,0,1,2017,0,5

In [25]:
# merge with all states
legality_merged_df = pd.merge(years_df, legality_df, on=['Rec Year Legalized', 'State', 'Recreational', 'Medical', 'Med Year Legalized'], how='outer')
legality_merged_df

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Alaska,1,2014,1,1998,8.0,24.0
1,Arizona,1,2020,1,2010,2.0,12.0
2,California,1,2016,1,1996,6.0,26.0
3,Colorado,1,2012,1,2000,10.0,22.0
4,Connecticut,1,2021,1,2012,1.0,10.0
5,District of Columbia,1,2015,1,2011,7.0,11.0
6,Illinois,1,2019,1,2013,3.0,9.0
7,Maine,1,2016,1,1999,6.0,23.0
8,Massachusetts,1,2016,1,2012,6.0,10.0
9,Michigan,1,2018,1,2008,4.0,14.0
10,Montana,1,2020,1,2004,2.0,18.0
11,Nevada,1,2016,1,1998,6.0,24.0
12,New Jersey,1,2020,1,2010,2.0,12.0
13,New Mexico,1,2021,1,2007,1.0,15.0
14,New York,1,2021,1,2014,1.0,8.0
15,Oregon,1,2014,1,1998,8.0,24.0
16,Rhode Island,1,2022,1,2006,0.0,16.0
17,Vermont,1,2020,1,2004,2.0,18.0
18,Virginia,1,2021,1,2020,1.0,2.0
19,Washington,1,2012,1,1998,10.0,24.0
20,Alabama,0,0,1,2021,0.0,1.0
21,Arkansas,0,0,1,2016,0.0,6.0
22,Delaware,0,0,1,2011,0.0,11.0
23,Florida,0,0,1,2016,0.0,6.0
24,Georgia,0,0,1,2015,0.0,7.0
25,Hawaii,0,0,1,2000,0.0,22.0
26,Iowa,0,0,1,2017,0.0,5.0
27,Louisiana,0,0,1,2015,0.0,7.0
28,Maryland,0,0,1,2013,0.0,9.0
29,Minnesota,0,0,1,2014,0.0,8.0
30,Mississippi,0,0,1,2022,0.0,0.0
31,Missouri,0,0,1,2018,0.0,4.0
32,New Hampshire,0,0,1,2013,0.0,9.0
33,North Dakota,0,0,1,2016,0.0,6.0
34,Ohio,0,0,1,2016,0.0,6.0
35,Oklahoma,0,0,1,2018,0.0,4.0
36,Pennsylvania,0,0,1,2016,0.0,6.0
37,South Dakota,0,0,1,2020,0.0,2.0
38,Utah,0,0,1,2018,0.0,4.0
39,West Virginia,0,0,1,2017,0.0,5.0
40,Idaho,0,0,0,0,NaN,NaN
41,Indiana,0,0,0,0,NaN,NaN
42,Kansas,0,0,0,0,NaN,NaN
43,Kentucky,0,0,0,0,NaN,NaN
44,Nebraska,0,0,0,0,NaN,NaN
45,North Carolina,0,0,0,0,NaN,NaN
46,South Carolina,0,0,0,0,NaN,NaN
47,Tennessee,0,0,0,0,NaN,NaN
48,Texas,0,0,0,0,NaN,NaN
49,Wisconsin,0,0,0,0,NaN,NaN
50,Wyoming,0,0,0,0,NaN,NaN

In [26]:
# Replace NaN with 0
legality_merged_df = legality_merged_df.fillna(0)
legality_merged_df

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Alaska,1,2014,1,1998,8.0,24.0
1,Arizona,1,2020,1,2010,2.0,12.0
2,California,1,2016,1,1996,6.0,26.0
3,Colorado,1,2012,1,2000,10.0,22.0
4,Connecticut,1,2021,1,2012,1.0,10.0
5,District of Columbia,1,2015,1,2011,7.0,11.0
6,Illinois,1,2019,1,2013,3.0,9.0
7,Maine,1,2016,1,1999,6.0,23.0
8,Massachusetts,1,2016,1,2012,6.0,10.0
9,Michigan,1,2018,1,2008,4.0,14.0
10,Montana,1,2020,1,2004,2.0,18.0
11,Nevada,1,2016,1,1998,6.0,24.0
12,New Jersey,1,2020,1,2010,2.0,12.0
13,New Mexico,1,2021,1,2007,1.0,15.0
14,New York,1,2021,1,2014,1.0,8.0
15,Oregon,1,2014,1,1998,8.0,24.0
16,Rhode Island,1,2022,1,2006,0.0,16.0
17,Vermont,1,2020,1,2004,2.0,18.0
18,Virginia,1,2021,1,2020,1.0,2.0
19,Washington,1,2012,1,1998,10.0,24.0
20,Alabama,0,0,1,2021,0.0,1.0
21,Arkansas,0,0,1,2016,0.0,6.0
22,Delaware,0,0,1,2011,0.0,11.0
23,Florida,0,0,1,2016,0.0,6.0
24,Georgia,0,0,1,2015,0.0,7.0
25,Hawaii,0,0,1,2000,0.0,22.0
26,Iowa,0,0,1,2017,0.0,5.0
27,Louisiana,0,0,1,2015,0.0,7.0
28,Maryland,0,0,1,2013,0.0,9.0
29,Minnesota,0,0,1,2014,0.0,8.0
30,Mississippi,0,0,1,2022,0.0,0.0
31,Missouri,0,0,1,2018,0.0,4.0
32,New Hampshire,0,0,1,2013,0.0,9.0
33,North Dakota,0,0,1,2016,0.0,6.0
34,Ohio,0,0,1,2016,0.0,6.0
35,Oklahoma,0,0,1,2018,0.0,4.0
36,Pennsylvania,0,0,1,2016,0.0,6.0
37,South Dakota,0,0,1,2020,0.0,2.0
38,Utah,0,0,1,2018,0.0,4.0
39,West Virginia,0,0,1,2017,0.0,5.0
40,Idaho,0,0,0,0,0.0,0.0
41,Indiana,0,0,0,0,0.0,0.0
42,Kansas,0,0,0,0,0.0,0.0
43,Kentucky,0,0,0,0,0.0,0.0
44,Nebraska,0,0,0,0,0.0,0.0
45,North Carolina,0,0,0,0,0.0,0.0
46,South Carolina,0,0,0,0,0.0,0.0
47,Tennessee,0,0,0,0,0.0,0.0
48,Texas,0,0,0,0,0.0,0.0
49,Wisconsin,0,0,0,0,0.0,0.0
50,Wyoming,0,0,0,0,0.0,0.0

In [29]:
legality_merged_df['Years legal (rec)'] = legality_merged_df['Years legal (rec)'].astype(int)
legality_merged_df['Years legal (med)'] = legality_merged_df['Years legal (med)'].astype(int)
legality_merged_df

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Alaska,1,2014,1,1998,8,24
1,Arizona,1,2020,1,2010,2,12
2,California,1,2016,1,1996,6,26
3,Colorado,1,2012,1,2000,10,22
4,Connecticut,1,2021,1,2012,1,10
5,District of Columbia,1,2015,1,2011,7,11
6,Illinois,1,2019,1,2013,3,9
7,Maine,1,2016,1,1999,6,23
8,Massachusetts,1,2016,1,2012,6,10
9,Michigan,1,2018,1,2008,4,14
10,Montana,1,2020,1,2004,2,18
11,Nevada,1,2016,1,1998,6,24
12,New Jersey,1,2020,1,2010,2,12
13,New Mexico,1,2021,1,2007,1,15
14,New York,1,2021,1,2014,1,8
15,Oregon,1,2014,1,1998,8,24
16,Rhode Island,1,2022,1,2006,0,16
17,Vermont,1,2020,1,2004,2,18
18,Virginia,1,2021,1,2020,1,2
19,Washington,1,2012,1,1998,10,24
20,Alabama,0,0,1,2021,0,1
21,Arkansas,0,0,1,2016,0,6
22,Delaware,0,0,1,2011,0,11
23,Florida,0,0,1,2016,0,6
24,Georgia,0,0,1,2015,0,7
25,Hawaii,0,0,1,2000,0,22
26,Iowa,0,0,1,2017,0,5
27,Louisiana,0,0,1,2015,0,7
28,Maryland,0,0,1,2013,0,9
29,Minnesota,0,0,1,2014,0,8
30,Mississippi,0,0,1,2022,0,0
31,Missouri,0,0,1,2018,0,4
32,New Hampshire,0,0,1,2013,0,9
33,North Dakota,0,0,1,2016,0,6
34,Ohio,0,0,1,2016,0,6
35,Oklahoma,0,0,1,2018,0,4
36,Pennsylvania,0,0,1,2016,0,6
37,South Dakota,0,0,1,2020,0,2
38,Utah,0,0,1,2018,0,4
39,West Virginia,0,0,1,2017,0,5
40,Idaho,0,0,0,0,0,0
41,Indiana,0,0,0,0,0,0
42,Kansas,0,0,0,0,0,0
43,Kentucky,0,0,0,0,0,0
44,Nebraska,0,0,0,0,0,0
45,North Carolina,0,0,0,0,0,0
46,South Carolina,0,0,0,0,0,0
47,Tennessee,0,0,0,0,0,0
48,Texas,0,0,0,0,0,0
49,Wisconsin,0,0,0,0,0,0
50,Wyoming,0,0,0,0,0,0

In [31]:
legality_merged_df.to_csv('../datasets/legality_merged.csv')