In [1]:
import pandas as pd
import numpy as np

In [4]:
# Load legality_merged_df
legality_merged_df = pd.read_csv("../datasets/legality_merged.csv")
legality_merged_df

,Unnamed: 0,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,0,Alaska,1,2014,1,1998,8,24
1,1,Arizona,1,2020,1,2010,2,12
2,2,California,1,2016,1,1996,6,26
3,3,Colorado,1,2012,1,2000,10,22
4,4,Connecticut,1,2021,1,2012,1,10
5,5,District of Columbia,1,2015,1,2011,7,11
6,6,Illinois,1,2019,1,2013,3,9
7,7,Maine,1,2016,1,1999,6,23
8,8,Massachusetts,1,2016,1,2012,6,10
9,9,Michigan,1,2018,1,2008,4,14
10,10,Montana,1,2020,1,2004,2,18
11,11,Nevada,1,2016,1,1998,6,24
12,12,New Jersey,1,2020,1,2010,2,12
13,13,New Mexico,1,2021,1,2007,1,15
14,14,New York,1,2021,1,2014,1,8
15,15,Oregon,1,2014,1,1998,8,24
16,16,Rhode Island,1,2022,1,2006,0,16
17,17,Vermont,1,2020,1,2004,2,18
18,18,Virginia,1,2021,1,2020,1,2
19,19,Washington,1,2012,1,1998,10,24
20,20,Alabama,0,0,1,2021,0,1
21,21,Arkansas,0,0,1,2016,0,6
22,22,Delaware,0,0,1,2011,0,11
23,23,Florida,0,0,1,2016,0,6
24,24,Georgia,0,0,1,2015,0,7
25,25,Hawaii,0,0,1,2000,0,22
26,26,Iowa,0,0,1,2017,0,5
27,27,Louisiana,0,0,1,2015,0,7
28,28,Maryland,0,0,1,2013,0,9
29,29,Minnesota,0,0,1,2014,0,8
30,30,Mississippi,0,0,1,2022,0,0
31,31,Missouri,0,0,1,2018,0,4
32,32,New Hampshire,0,0,1,2013,0,9
33,33,North Dakota,0,0,1,2016,0,6
34,34,Ohio,0,0,1,2016,0,6
35,35,Oklahoma,0,0,1,2018,0,4
36,36,Pennsylvania,0,0,1,2016,0,6
37,37,South Dakota,0,0,1,2020,0,2
38,38,Utah,0,0,1,2018,0,4
39,39,West Virginia,0,0,1,2017,0,5
40,40,Idaho,0,0,0,0,0,0
41,41,Indiana,0,0,0,0,0,0
42,42,Kansas,0,0,0,0,0,0
43,43,Kentucky,0,0,0,0,0,0
44,44,Nebraska,0,0,0,0,0,0
45,45,North Carolina,0,0,0,0,0,0
46,46,South Carolina,0,0,0,0,0,0
47,47,Tennessee,0,0,0,0,0,0
48,48,Texas,0,0,0,0,0,0
49,49,Wisconsin,0,0,0,0,0,0
50,50,Wyoming,0,0,0,0,0,0

In [9]:
# Drop first column
legality_merged_df = legality_merged_df.drop(columns=["Unnamed: 0"])
legality_merged_df

,State,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Alaska,1,2014,1,1998,8,24
1,Arizona,1,2020,1,2010,2,12
2,California,1,2016,1,1996,6,26
3,Colorado,1,2012,1,2000,10,22
4,Connecticut,1,2021,1,2012,1,10
5,District of Columbia,1,2015,1,2011,7,11
6,Illinois,1,2019,1,2013,3,9
7,Maine,1,2016,1,1999,6,23
8,Massachusetts,1,2016,1,2012,6,10
9,Michigan,1,2018,1,2008,4,14
10,Montana,1,2020,1,2004,2,18
11,Nevada,1,2016,1,1998,6,24
12,New Jersey,1,2020,1,2010,2,12
13,New Mexico,1,2021,1,2007,1,15
14,New York,1,2021,1,2014,1,8
15,Oregon,1,2014,1,1998,8,24
16,Rhode Island,1,2022,1,2006,0,16
17,Vermont,1,2020,1,2004,2,18
18,Virginia,1,2021,1,2020,1,2
19,Washington,1,2012,1,1998,10,24
20,Alabama,0,0,1,2021,0,1
21,Arkansas,0,0,1,2016,0,6
22,Delaware,0,0,1,2011,0,11
23,Florida,0,0,1,2016,0,6
24,Georgia,0,0,1,2015,0,7
25,Hawaii,0,0,1,2000,0,22
26,Iowa,0,0,1,2017,0,5
27,Louisiana,0,0,1,2015,0,7
28,Maryland,0,0,1,2013,0,9
29,Minnesota,0,0,1,2014,0,8
30,Mississippi,0,0,1,2022,0,0
31,Missouri,0,0,1,2018,0,4
32,New Hampshire,0,0,1,2013,0,9
33,North Dakota,0,0,1,2016,0,6
34,Ohio,0,0,1,2016,0,6
35,Oklahoma,0,0,1,2018,0,4
36,Pennsylvania,0,0,1,2016,0,6
37,South Dakota,0,0,1,2020,0,2
38,Utah,0,0,1,2018,0,4
39,West Virginia,0,0,1,2017,0,5
40,Idaho,0,0,0,0,0,0
41,Indiana,0,0,0,0,0,0
42,Kansas,0,0,0,0,0,0
43,Kentucky,0,0,0,0,0,0
44,Nebraska,0,0,0,0,0,0
45,North Carolina,0,0,0,0,0,0
46,South Carolina,0,0,0,0,0,0
47,Tennessee,0,0,0,0,0,0
48,Texas,0,0,0,0,0,0
49,Wisconsin,0,0,0,0,0,0
50,Wyoming,0,0,0,0,0,0

In [10]:
legality_merged_df.dtypes

State                 object
Recreational           int64
Rec Year Legalized     int64
Medical                int64
Med Year Legalized     int64
Years legal (rec)      int64
Years legal (med)      int64
dtype: object

In [11]:
# Load percap_data
percap_data = pd.read_csv("../finalized_datasets/percap_data.csv")
percap_data

,Unnamed: 0,State,Year,Population,Number of Cannabis Users,Number of Opioid Deaths,Per Capita Cannabis Use,Per Capita Opioid Deaths
0,0,Total U.S.,2014,318386329,34038000,47055,0.106908,0.000148
1,1,Total U.S.,2015,320738994,35584000,52404,0.110944,0.000163
2,2,Total U.S.,2016,323071755,36806000,63450,0.113925,0.000196
3,3,Total U.S.,2017,325122128,39252000,70237,0.120730,0.000216
4,4,Total U.S.,2018,326838199,42211000,56144,0.129150,0.000172
...,...,...,...,...,...,...,...,...
349,349,Virginia,2020,8590563,959000,2240,0.111634,0.000261
350,350,Washington,2020,7693612,1715000,1733,0.222912,0.000225
351,351,West Virginia,2020,1784787,214000,1330,0.119902,0.000745
352,352,Wisconsin,2020,5832655,765000,1531,0.131158,0.000262
353,353,Wyoming,2020,582328,67000,99,0.115055,0.000170

In [12]:
percap_data = percap_data.drop(columns=['Unnamed: 0'])
percap_data

,State,Year,Population,Number of Cannabis Users,Number of Opioid Deaths,Per Capita Cannabis Use,Per Capita Opioid Deaths
0,Total U.S.,2014,318386329,34038000,47055,0.106908,0.000148
1,Total U.S.,2015,320738994,35584000,52404,0.110944,0.000163
2,Total U.S.,2016,323071755,36806000,63450,0.113925,0.000196
3,Total U.S.,2017,325122128,39252000,70237,0.120730,0.000216
4,Total U.S.,2018,326838199,42211000,56144,0.129150,0.000172
...,...,...,...,...,...,...,...
349,Virginia,2020,8590563,959000,2240,0.111634,0.000261
350,Washington,2020,7693612,1715000,1733,0.222912,0.000225
351,West Virginia,2020,1784787,214000,1330,0.119902,0.000745
352,Wisconsin,2020,5832655,765000,1531,0.131158,0.000262
353,Wyoming,2020,582328,67000,99,0.115055,0.000170

In [13]:
mega_merged = pd.merge(percap_data, legality_merged_df, on=['State'], how='outer')
mega_merged

,State,Year,Population,Number of Cannabis Users,Number of Opioid Deaths,Per Capita Cannabis Use,Per Capita Opioid Deaths,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Total U.S.,2014,318386329,34038000,47055,0.106908,0.000148,NaN,NaN,NaN,NaN,NaN,NaN
1,Total U.S.,2015,320738994,35584000,52404,0.110944,0.000163,NaN,NaN,NaN,NaN,NaN,NaN
2,Total U.S.,2016,323071755,36806000,63450,0.113925,0.000196,NaN,NaN,NaN,NaN,NaN,NaN
3,Total U.S.,2017,325122128,39252000,70237,0.120730,0.000216,NaN,NaN,NaN,NaN,NaN,NaN
4,Total U.S.,2018,326838199,42211000,56144,0.129150,0.000172,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,Arkansas,2016,2991815,274000,401,0.091583,0.000134,0.0,0.0,1.0,2016.0,0.0,6.0
350,Arkansas,2017,3003855,312000,446,0.103867,0.000148,0.0,0.0,1.0,2016.0,0.0,6.0
351,Arkansas,2018,3012161,333000,444,0.110552,0.000147,0.0,0.0,1.0,2016.0,0.0,6.0
352,Arkansas,2019,3020985,338000,388,0.111884,0.000128,0.0,0.0,1.0,2016.0,0.0,6.0
353,Arkansas,2020,3030522,372000,546,0.122751,0.000180,0.0,0.0,1.0,2016.0,0.0,6.0

In [14]:
# Replace NaN with 0
mega_merged = mega_merged.fillna(0)
mega_merged

,State,Year,Population,Number of Cannabis Users,Number of Opioid Deaths,Per Capita Cannabis Use,Per Capita Opioid Deaths,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Total U.S.,2014,318386329,34038000,47055,0.106908,0.000148,0.0,0.0,0.0,0.0,0.0,0.0
1,Total U.S.,2015,320738994,35584000,52404,0.110944,0.000163,0.0,0.0,0.0,0.0,0.0,0.0
2,Total U.S.,2016,323071755,36806000,63450,0.113925,0.000196,0.0,0.0,0.0,0.0,0.0,0.0
3,Total U.S.,2017,325122128,39252000,70237,0.120730,0.000216,0.0,0.0,0.0,0.0,0.0,0.0
4,Total U.S.,2018,326838199,42211000,56144,0.129150,0.000172,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,Arkansas,2016,2991815,274000,401,0.091583,0.000134,0.0,0.0,1.0,2016.0,0.0,6.0
350,Arkansas,2017,3003855,312000,446,0.103867,0.000148,0.0,0.0,1.0,2016.0,0.0,6.0
351,Arkansas,2018,3012161,333000,444,0.110552,0.000147,0.0,0.0,1.0,2016.0,0.0,6.0
352,Arkansas,2019,3020985,338000,388,0.111884,0.000128,0.0,0.0,1.0,2016.0,0.0,6.0
353,Arkansas,2020,3030522,372000,546,0.122751,0.000180,0.0,0.0,1.0,2016.0,0.0,6.0

In [15]:
# Convert to int
mega_merged['Years legal (rec)'] = mega_merged['Years legal (rec)'].astype(int)
mega_merged['Years legal (med)'] = mega_merged['Years legal (med)'].astype(int)
mega_merged['Recreational'] = mega_merged['Recreational'].astype(int)
mega_merged['Medical'] = mega_merged['Medical'].astype(int)
mega_merged['Rec Year Legalized'] = mega_merged['Rec Year Legalized'].astype(int)
mega_merged['Med Year Legalized'] = mega_merged['Med Year Legalized'].astype(int)
mega_merged

,State,Year,Population,Number of Cannabis Users,Number of Opioid Deaths,Per Capita Cannabis Use,Per Capita Opioid Deaths,Recreational,Rec Year Legalized,Medical,Med Year Legalized,Years legal (rec),Years legal (med)
0,Total U.S.,2014,318386329,34038000,47055,0.106908,0.000148,0,0,0,0,0,0
1,Total U.S.,2015,320738994,35584000,52404,0.110944,0.000163,0,0,0,0,0,0
2,Total U.S.,2016,323071755,36806000,63450,0.113925,0.000196,0,0,0,0,0,0
3,Total U.S.,2017,325122128,39252000,70237,0.120730,0.000216,0,0,0,0,0,0
4,Total U.S.,2018,326838199,42211000,56144,0.129150,0.000172,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,Arkansas,2016,2991815,274000,401,0.091583,0.000134,0,0,1,2016,0,6
350,Arkansas,2017,3003855,312000,446,0.103867,0.000148,0,0,1,2016,0,6
351,Arkansas,2018,3012161,333000,444,0.110552,0.000147,0,0,1,2016,0,6
352,Arkansas,2019,3020985,338000,388,0.111884,0.000128,0,0,1,2016,0,6
353,Arkansas,2020,3030522,372000,546,0.122751,0.000180,0,0,1,2016,0,6

In [18]:
mega_merged.to_csv('../finalized_datasets/mega_merged.csv')